### PR TITLE
Update Bard.php

### PR DESCRIPTION
**Pull request by pixkk**
Fix: From this moment we need use two cookies - __Secure-1PSID and __Secure-1PSIDTS

Update: The "bl" parameter (in html code it`s cfb2h) is now obtained automatically from the html page.

### CODE REVIEW

**Comment by pj8912** [comment]
did you test it?

**Comment by pixkk** [comment]
Certainly. Without this, my code doesn't work.

**Comment by pj8912** [comment]
I am busy with work so I have no time to test this , can you post your working example up here, code and video would be fine.

**Comment by correosteve** [comment]
there a semi colon missing in the cURL cookie string separating the cookies as there's now two.  It does work with this amendment, however it was working on the original code anyway for me (although does tend to stop for a long while from overuse)

**Comment by pixkk** [comment]
Okay. 
image
It`s test code.

**Result without editing file (one cookie). I`m use constants for me, but in pull request used ENV:**
Code: 
image

Result: 
image

**Result with editing file (two cookies). I`m use constants for me, but in pull request used ENV:**
Code:
image
Result:
image

**Comment by pixkk** [comment]
Also the values of these cookies may change at random times.

**Comment by pixkk** [comment]
> there a semi colon missing in the cURL cookie string separating the cookies as there's now two.

Yes, forgot him*. Added a semicolon in place.

**Comment by pj8912** [comment]
great!, so `print($result['choices'][0]['content'][0]);` for reply

**Comment by pixkk** [comment]
image

I also want to add that the value of __Secure-1PSIDTS will have to be changed frequently (Google changes it). At the moment, I have not delved into the mechanism for changing the value of this cookie, but it is important to focus on this.

**Comment by pj8912** [comment]
Will update README on this

**Pull request merged**
